#include "hashTable.h"
#include <iostream>
#include <unistd.h>

// Create a hash function that will turn our address into a value between 0 and N - 1

hashTable::hashTable() { 
    this->capacity = 100; // Initial capacity
    this->numBytes = sizeof(HashEntry) * capacity; // Initial number of bytes allocated
    
    currEntry = static_cast<HashEntry*>(mmap(nullptr, numBytes, PROT_READ | PROT_WRITE, MAP_ANONYMOUS | MAP_SHARED, -1, 0)); // Allocate memory for the hash table

    if (currEntry == MAP_FAILED) {
        throw new std::runtime_error("Failed to map address on byte size: " + std::to_string(numBytes));
    } // Catches in case of memory mapping failure

    size = 0; // Initial size

    for(size_t i = 0; i < capacity; i++) {
        currEntry[i].address = nullptr;
        currEntry[i].allocationSize = 0;
        currEntry[i].state = State::Free;
    }
}

hashTable::~hashTable() { 
    if (currEntry != nullptr) {
        munmap(currEntry, numBytes);
        currEntry = nullptr;
    }

    capacity = 0;
    numBytes = 0;
}

int hashTable::hash(void* add) {
    uintptr_t addr = reinterpret_cast<uintptr_t>(add);
    addr ^= (addr >> 33); // Since mmap returns page aligned addresses, we know the lower 12 bits are 0, XOR shift
    // moves those bits down before using modulo to prevent addresses from hashing to 0
    addr *= 0xff51afd7ed558ccdULL; // Multiplying with a prime number creates more diversity between similar inputs.
    addr ^= (addr >> 33); // Removes any detectable patterns
    return addr % capacity; // Ensures value is less than capacity
} // This hashing algorithm was generated by AI, I made sure to understand what it does before proceeding

int hashTable::find(void* desiredAddress) {
    int h = hash(desiredAddress); // hashedAddress of the input address
    int iter = h;
    bool search = true; // Continues to search in while loop

    while(search) {
        if (currEntry[iter].address == desiredAddress) {
            return iter;
        }
        else if(currEntry[iter].state == State::Free) {
            search = false;
        }

        iter++;

        if(iter >= capacity) {
            iter = 0;
        }
        if(iter == h) {
            search = false;
        }
    }
    return -1; // Address not found
} // Should be O(1)

void hashTable::grow() {
    size_t oldCapacity = capacity;
    size_t oldBytes = numBytes;
    HashEntry* oldTable = currEntry;
    capacity = oldCapacity * 2;
    numBytes = sizeof(HashEntry) * capacity; // Initial number of bytes allocated
    currEntry = static_cast<HashEntry*>(mmap(nullptr, numBytes, PROT_READ | PROT_WRITE, MAP_ANONYMOUS | MAP_SHARED, -1, 0)); // Allocate memory for the hash table

    // Check for mmap failure
    if (currEntry == MAP_FAILED) {
        currEntry = oldTable; // Restore old table
        capacity = oldCapacity;
        numBytes = oldBytes;
        throw std::runtime_error("Failed to grow hash table: mmap() returned MAP_FAILED for size " + std::to_string(numBytes));
    }

    for (size_t i = 0; i < capacity; i++) {
        currEntry[i].address = nullptr;
        currEntry[i].allocationSize = 0;
        currEntry[i].state = State::Free;
    }
    size = 0;

    for(size_t i = 0; i < oldCapacity; i++) {
        if(oldTable[i].state == State::Occupied) {
            insert(oldTable[i].address, oldTable[i].allocationSize);
        }
    }
    munmap(oldTable, oldBytes);
}

void hashTable::insert(void* address, size_t sizeOfAllocation) {
    // Check if address already exists (duplicate key check)
    int existingIndex = find(address);
    if (existingIndex != -1) {
        // Address already exists - don't insert again
        throw std::runtime_error("Duplicate allocation: address " + std::to_string(reinterpret_cast<uintptr_t>(address)) + 
                                 " is already in the hash table");
    }

    if(this->size >= this->capacity * 0.7) {
        this->grow(); // Grow the hash table if the size exceeds the capacity
    }

    int iter = hash(address); // hashedAddress of the input address

    while(true) {
        if (currEntry[iter].state == State::Occupied) {
            iter = (iter + 1) % capacity;
        }
        else {
            currEntry[iter].allocationSize = sizeOfAllocation;
            currEntry[iter].address = address; // Insert the address into the hash table
            currEntry[iter].state = State::Occupied;
            size++; // Increment the size of the hash table
            break;
        }
    }
}

size_t hashTable::remove(void* address) {
    size_t sizeOfAllocation;
    int foundAddress = find(address);

    if(foundAddress == -1) {
        return -1;
    }

    currEntry[foundAddress].address = nullptr; // Remove the address from the hash table
    sizeOfAllocation = currEntry[foundAddress].allocationSize;
    currEntry[foundAddress].state = State::Deleted;
    this->size--; // Decrement the size of the hash table

    return sizeOfAllocation;
}

void* hashTable::getAddress(int location) {
    return currEntry[location].address;
}

State hashTable::getState(int location) {
    return currEntry[location].state;
}

size_t hashTable::getSize() {
    return this->size;
}

size_t hashTable::getCapacity() {
    return this->capacity;
}