import matplotlib.pyplot as plt

def load_csv(filename):
    with open(filename, 'r') as f:
        lines = f.readlines()

    headers = lines[0].strip().split(",")
    data = {h: [] for h in headers}

    for line in lines[1:]:
        cols = line.strip().split(",")
        for i, col in enumerate(cols):
            data[headers[i]].append(float(col))

    return data


def main():
    # The three CSV files generated by your Java code
    files = {
        "Threshold 0": "MergeSortT.csv",
        "Threshold 5": "MergeSortT0.csv",
        "Threshold 10": "MergeSortT1.csv",
        "Threshold 20": "MergeSortT2.csv",
        "Threshold 30": "MergeSortT3.csv",
        "Threshold 40": "MergeSortT4.csv",
        "Threshold 50": "MergeSortT5.csv",
    }

    plt.figure(figsize=(10,6))

    for label, filename in files.items():
        data = load_csv(filename)
        plt.plot(
            data["N"],
            data["Time(ns)"],
            marker='o',
            label=label,
        )

    plt.xlabel("N (input size)")
    plt.ylabel("Average Time (ns)")
    plt.yscale('log')
    plt.title("MergeSort Thresholds Comparison")

    plt.legend()
    plt.grid(True)

    plt.savefig("MergeSort Thresholds Comparison.png", dpi = 150)
    plt.show()
    plt.close()


if __name__ == "__main__":
    main()