import matplotlib.pyplot as plt

def load_csv(filename):
    with open(filename, 'r') as f:
        lines = f.readlines()

    headers = lines[0].strip().split(",")
    data = {h: [] for h in headers}

    for line in lines[1:]:
        cols = line.strip().split(",")
        for i, col in enumerate(cols):
            data[headers[i]].append(float(col))

    return data


def main():
    # The three CSV files generated by your Java code
    files = {
        "Array Stack Push": "ArrayStackPush.csv",
        "Linked List Stack Push": "LinkedListStackPush.csv",
        "Array Stack Pop": "ArrayStackPop.csv",
        "Linked List Stack Pop": "LinkedListStackPop.csv",
        "Array Stack Peek": "ArrayStackPeek.csv",
        "Linked List Stack Peek": "LinkedListStackPeek.csv",
    }

    plt.figure(figsize=(10,6))

    for label, filename in files.items():
        data = load_csv(filename)
        plt.plot(
            data["N"],
            data["Time(ns)"],
            marker='o',
            label=label,
        )

    plt.xlabel("N (input size)")
    plt.ylabel("Average Time (ns)")
    plt.xscale('log')
    plt.title("Linked List Stack vs Array Stack")

    plt.legend()
    plt.grid(True)

    plt.savefig("Array Stack v Linked List Stack Comparison.png", dpi = 150)
    plt.show()
    plt.close()


if __name__ == "__main__":
    main()